# Generated by Django 5.2.8 on 2025-12-11 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_habit_created_at_alter_habit_name_habitlog_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='habitlog',
            unique_together={('habit', 'date')},
        ),
    ]
